# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 780778d1eafeb3bc4e144d3b53872a3d0fcf0cf39c1382ad5f598e0f6e69fe594a2952498a77be65ed82024ce6a83f92d9c1a00ec7470f3400d6a735b77e434f

test:
  secret_key_base: fdf02284355b36d2179161b7d33c7c6103a10515615b1342d53d14393a5d1d4aa07b35868a573be06bddc98b38365533dc82efb53dcc0d47da72519d58e0fc1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
